# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 585)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 700))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(230, 130, 301, 281))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color:#2A5B72; color: white; ")
        self.widget.setObjectName("widget")
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setGeometry(QtCore.QRect(140, 170, 113, 32))
        self.loginButton.setStyleSheet("font-weight: bold;")
        self.loginButton.setObjectName("loginButton")

        self.loginButton.clicked.connect(self.sqlite)


        self.passwdLabel = QtWidgets.QLabel(self.widget)
        self.passwdLabel.setGeometry(QtCore.QRect(40, 140, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passwdLabel.setFont(font)
        self.passwdLabel.setStyleSheet("font-weight: bold;")
        self.passwdLabel.setObjectName("passwdLabel")
        self.userLabel = QtWidgets.QLabel(self.widget)
        self.userLabel.setGeometry(QtCore.QRect(40, 110, 60, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userLabel.setFont(font)
        self.userLabel.setStyleSheet("font-weight: bold;")
        self.userLabel.setObjectName("userLabel")
        self.user = QtWidgets.QPlainTextEdit(self.widget)
        self.user.setGeometry(QtCore.QRect(140, 110, 111, 16))
        self.user.setStyleSheet("background-color: white;")
        self.user.setBackgroundVisible(False)
        self.user.setPlaceholderText("")
        self.user.setObjectName("user")
        self.passwd = QtWidgets.QPlainTextEdit(self.widget)
        self.passwd.setGeometry(QtCore.QRect(140, 140, 111, 16))
        self.passwd.setStyleSheet("background-color: white;")
        self.passwd.setObjectName("passwd")
        self.title = QtWidgets.QLabel(self.widget)
        self.title.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.passwdLabel.setText(_translate("MainWindow", "Contraseña"))
        self.userLabel.setText(_translate("MainWindow", "Usuario"))
        self.title.setText(_translate("MainWindow", "PARKTHON"))

    def sqlite(self):
        print(self.passwd.toPlainText())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
